/**
 * UI Configuration
 * Controls various UI features and behaviors
 */

export interface UIConfig {
  // Auto-generated UI components
  enableAutoGeneratedUI: boolean;
  
  // Debug mode
  enableDebugMode: boolean;
  
  // Feedback system
  enableFeedbackSystem: boolean;
  
  // AI Elements integration
  enableAIElements: boolean;
}

export const defaultUIConfig: UIConfig = {
  // Disable auto-generated UI by default - markdown is already excellent
  enableAutoGeneratedUI: false,
  
  // Debug mode off by default
  enableDebugMode: false,
  
  // Feedback system enabled by default
  enableFeedbackSystem: true,
  
  // AI Elements enabled by default
  enableAIElements: true,
};

/**
 * Get UI configuration with environment variable overrides
 * Note: In Cloudflare Workers, env vars are only available server-side
 * For client-side, we use the default config or localStorage overrides
 */
export function getUIConfig(): UIConfig {
  // Check if we're in a browser environment
  if (typeof window !== 'undefined') {
    // Client-side: use localStorage for overrides or default config
    return {
      enableAutoGeneratedUI: localStorage.getItem('ENABLE_AUTO_GENERATED_UI') === 'true' || defaultUIConfig.enableAutoGeneratedUI,
      enableDebugMode: localStorage.getItem('ENABLE_DEBUG_MODE') === 'true' || defaultUIConfig.enableDebugMode,
      enableFeedbackSystem: localStorage.getItem('ENABLE_FEEDBACK_SYSTEM') !== 'false' && defaultUIConfig.enableFeedbackSystem,
      enableAIElements: localStorage.getItem('ENABLE_AI_ELEMENTS') !== 'false' && defaultUIConfig.enableAIElements,
    };
  }
  
  // Server-side: use default config (env vars would be handled by the worker)
  return defaultUIConfig;
}

/**
 * Check if auto-generated UI should be enabled
 */
export function shouldEnableAutoGeneratedUI(): boolean {
  return getUIConfig().enableAutoGeneratedUI;
}

/**
 * Check if debug mode should be enabled
 */
export function shouldEnableDebugMode(): boolean {
  return getUIConfig().enableDebugMode;
}

/**
 * Check if feedback system should be enabled
 */
export function shouldEnableFeedbackSystem(): boolean {
  return getUIConfig().enableFeedbackSystem;
}

/**
 * Check if AI Elements should be enabled
 */
export function shouldEnableAIElements(): boolean {
  return getUIConfig().enableAIElements;
}

/**
 * Server-side configuration for Cloudflare Workers
 * This function should be used in the worker environment where env vars are available
 */
export function getServerUIConfig(env: any): UIConfig {
  return {
    enableAutoGeneratedUI: env?.ENABLE_AUTO_GENERATED_UI === 'true' || defaultUIConfig.enableAutoGeneratedUI,
    enableDebugMode: env?.ENABLE_DEBUG_MODE === 'true' || defaultUIConfig.enableDebugMode,
    enableFeedbackSystem: env?.ENABLE_FEEDBACK_SYSTEM !== 'false' && defaultUIConfig.enableFeedbackSystem,
    enableAIElements: env?.ENABLE_AI_ELEMENTS !== 'false' && defaultUIConfig.enableAIElements,
  };
}

/**
 * Update client-side configuration via localStorage
 */
export function updateClientUIConfig(config: Partial<UIConfig>): void {
  if (typeof window === 'undefined') return;
  
  Object.entries(config).forEach(([key, value]) => {
    if (value !== undefined) {
      localStorage.setItem(key.toUpperCase(), String(value));
    }
  });
}
